//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

using System.Web.Services.Protocols;

namespace GENERIC
{
    [System.CodeDom.Compiler.GeneratedCode("System.Xml", "2.0.50727.5420")]
    [System.Serializable()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/ws/2002/12/secext")]
    [System.Xml.Serialization.XmlRoot(Namespace = "http://schemas.xmlsoap.org/ws/2002/12/secext", IsNullable = false)]
    public partial class Security : SoapHeader
    {
        private SecurityUsernameToken usernameTokenField;

        public Security() : base()
        {
            this.usernameTokenField = new SecurityUsernameToken();
        }

        public Security(string utilizador, string senha, string criacao, string nonce) : this()
        {
            usernameTokenField.Username = utilizador;
            usernameTokenField.Password = senha;
            usernameTokenField.Nonce = nonce;
            usernameTokenField.Created = criacao;
        }

        [System.Xml.Serialization.XmlElement(Order = 0)]
        public SecurityUsernameToken UsernameToken
        {
            get
            {
                return this.usernameTokenField;
            }
            set
            {
                this.usernameTokenField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("System.Xml", "2.0.50727.5420")]
    [System.Serializable()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/ws/2002/12/secext")]
    public partial class SecurityUsernameToken
    {
        private string usernameField;

        private string passwordField;

        private string nonceField;

        private string createdField;

        [System.Xml.Serialization.XmlElement(Order = 0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        [System.Xml.Serialization.XmlElement(Order = 1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        [System.Xml.Serialization.XmlElement(Order = 2)]
        public string Nonce
        {
            get
            {
                return this.nonceField;
            }
            set
            {
                this.nonceField = value;
            }
        }

        [System.Xml.Serialization.XmlElement(Order = 3)]
        public string Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
    }
}


namespace TesteSeriesAT.SeriesAT {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;

    public enum TipoDocumentoSerie
    {
        FT,   //Fatura SI 
        FS,    //Fatura simplificada SI 
        FR,    //Fatura-recibo SI 
        ND,    //Nota de débito SI 
        NC,    //Nota de crédito SI 
        GR,    //Guia de remessa MG 
        GT,   //Guia de transporte MG 
        GA,    //Guia de movimentação de ativos fixos próprios MG 
        GC,    //Guia de consignação MG 
        GD,   //Guia ou nota de devolução MG 
        CM,    //Consultas de mesa WD 
        CC,   //Crédito de consignação WD 
        FC,   //Fatura de consignação WD 
        FO,    //Folhas de obra WD 
        NE,    //Nota de encomenda WD 
        OU,    //Outros WD 
        OR,    //Orçamentos WD 
        PF,    //Pró-forma WD 
        RP,    //Prémio ou recibo de prémio WD 
        RE,    //Estorno ou recibo de estorno WD 
        CS,    //Imputação a cosseguradoras WD 
        LD,    //Imputação a cosseguradora líder WD
    }

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SeriesWSPortBinding", Namespace="http://at.gov.pt/")]
    public partial class SeriesWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback registarSerieOperationCompleted;
        
        private System.Threading.SendOrPostCallback finalizarSerieOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarSeriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback anularSerieOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SeriesWSService() {
            this.Url = global::TesteSeriesAT.Properties.Settings.Default.WindowsFormsApp2_SeriesAT_SeriesWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        private GENERIC.Security _security;
        public GENERIC.Security SecurityToken
        {
            get
            {
                return _security;
            }
            set
            {
                _security = value;
            }
        }


        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public String daClasse(TipoDocumentoSerie tipoDoc)
        {
            switch (tipoDoc)
            {

                case TipoDocumentoSerie.FT:
                case TipoDocumentoSerie.FS:
                case TipoDocumentoSerie.FR:
                case TipoDocumentoSerie.ND:
                case TipoDocumentoSerie.NC:
                    return "SI";
                case TipoDocumentoSerie.GR:
                case TipoDocumentoSerie.GT:
                case TipoDocumentoSerie.GA:
                case TipoDocumentoSerie.GC:
                case TipoDocumentoSerie.GD:
                    return "MG";
                case TipoDocumentoSerie.CM:
                case TipoDocumentoSerie.CC:
                case TipoDocumentoSerie.FC:
                case TipoDocumentoSerie.FO:
                case TipoDocumentoSerie.NE:
                case TipoDocumentoSerie.OU:
                case TipoDocumentoSerie.OR:
                case TipoDocumentoSerie.PF:
                case TipoDocumentoSerie.RP:
                case TipoDocumentoSerie.RE:
                case TipoDocumentoSerie.CS:
                case TipoDocumentoSerie.LD:
                    return "WD";
            }

            return "";
        }

        public seriesResp RegistaSerie(TipoDocumentoSerie tipoDoc, String serie, int numero_inicial, DateTime dataInicial, String numCertificado)
        {
            return registarSerie(serie, "N", daClasse(tipoDoc), Enum.GetName(typeof(TipoDocumentoSerie), tipoDoc), numero_inicial.ToString(), dataInicial, numCertificado, "PI");
        }

        /// <remarks/>
        public event registarSerieCompletedEventHandler registarSerieCompleted;
        
        /// <remarks/>
        public event finalizarSerieCompletedEventHandler finalizarSerieCompleted;
        
        /// <remarks/>
        public event consultarSeriesCompletedEventHandler consultarSeriesCompleted;
        
        /// <remarks/>
        public event anularSerieCompletedEventHandler anularSerieCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeader("SecurityToken")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://at.gov.pt/", ResponseNamespace="http://at.gov.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("registarSerieResp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesResp registarSerie([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string serie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoSerie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string classeDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")] string numInicialSeq, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime dataInicioPrevUtiliz, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")] string numCertSWFatur, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string meioProcessamento) {
            object[] results = this.Invoke("registarSerie", new object[] {
                        serie,
                        tipoSerie,
                        classeDoc,
                        tipoDoc,
                        numInicialSeq,
                        dataInicioPrevUtiliz,
                        numCertSWFatur,
                        meioProcessamento});
            return ((seriesResp)(results[0]));
        }
        
        /// <remarks/>
        public void registarSerieAsync(string serie, string tipoSerie, string classeDoc, string tipoDoc, string numInicialSeq, System.DateTime dataInicioPrevUtiliz, string numCertSWFatur, string meioProcessamento) {
            this.registarSerieAsync(serie, tipoSerie, classeDoc, tipoDoc, numInicialSeq, dataInicioPrevUtiliz, numCertSWFatur, meioProcessamento, null);
        }
        
        /// <remarks/>
        public void registarSerieAsync(string serie, string tipoSerie, string classeDoc, string tipoDoc, string numInicialSeq, System.DateTime dataInicioPrevUtiliz, string numCertSWFatur, string meioProcessamento, object userState) {
            if ((this.registarSerieOperationCompleted == null)) {
                this.registarSerieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistarSerieOperationCompleted);
            }
            this.InvokeAsync("registarSerie", new object[] {
                        serie,
                        tipoSerie,
                        classeDoc,
                        tipoDoc,
                        numInicialSeq,
                        dataInicioPrevUtiliz,
                        numCertSWFatur,
                        meioProcessamento}, this.registarSerieOperationCompleted, userState);
        }
        
        private void OnregistarSerieOperationCompleted(object arg) {
            if ((this.registarSerieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registarSerieCompleted(this, new registarSerieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://at.gov.pt/", ResponseNamespace="http://at.gov.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("finalizarSerieResp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesResp finalizarSerie([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string serie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string classeDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string codValidacaoSerie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")] string seqUltimoDocEmitido, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string justificacao) {
            object[] results = this.Invoke("finalizarSerie", new object[] {
                        serie,
                        classeDoc,
                        tipoDoc,
                        codValidacaoSerie,
                        seqUltimoDocEmitido,
                        justificacao});
            return ((seriesResp)(results[0]));
        }
        
        /// <remarks/>
        public void finalizarSerieAsync(string serie, string classeDoc, string tipoDoc, string codValidacaoSerie, string seqUltimoDocEmitido, string justificacao) {
            this.finalizarSerieAsync(serie, classeDoc, tipoDoc, codValidacaoSerie, seqUltimoDocEmitido, justificacao, null);
        }
        
        /// <remarks/>
        public void finalizarSerieAsync(string serie, string classeDoc, string tipoDoc, string codValidacaoSerie, string seqUltimoDocEmitido, string justificacao, object userState) {
            if ((this.finalizarSerieOperationCompleted == null)) {
                this.finalizarSerieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinalizarSerieOperationCompleted);
            }
            this.InvokeAsync("finalizarSerie", new object[] {
                        serie,
                        classeDoc,
                        tipoDoc,
                        codValidacaoSerie,
                        seqUltimoDocEmitido,
                        justificacao}, this.finalizarSerieOperationCompleted, userState);
        }
        
        private void OnfinalizarSerieOperationCompleted(object arg) {
            if ((this.finalizarSerieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.finalizarSerieCompleted(this, new finalizarSerieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://at.gov.pt/", ResponseNamespace="http://at.gov.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarSeriesResp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public consultSeriesResp consultarSeries([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string serie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoSerie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string classeDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string codValidacaoSerie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime dataRegistoDe, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool dataRegistoDeSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime dataRegistoAte, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool dataRegistoAteSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string estado, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string meioProcessamento) {
            object[] results = this.Invoke("consultarSeries", new object[] {
                        serie,
                        tipoSerie,
                        classeDoc,
                        tipoDoc,
                        codValidacaoSerie,
                        dataRegistoDe,
                        dataRegistoDeSpecified,
                        dataRegistoAte,
                        dataRegistoAteSpecified,
                        estado,
                        meioProcessamento});
            return ((consultSeriesResp)(results[0]));
        }
        
        /// <remarks/>
        public void consultarSeriesAsync(string serie, string tipoSerie, string classeDoc, string tipoDoc, string codValidacaoSerie, System.DateTime dataRegistoDe, bool dataRegistoDeSpecified, System.DateTime dataRegistoAte, bool dataRegistoAteSpecified, string estado, string meioProcessamento) {
            this.consultarSeriesAsync(serie, tipoSerie, classeDoc, tipoDoc, codValidacaoSerie, dataRegistoDe, dataRegistoDeSpecified, dataRegistoAte, dataRegistoAteSpecified, estado, meioProcessamento, null);
        }
        
        /// <remarks/>
        public void consultarSeriesAsync(string serie, string tipoSerie, string classeDoc, string tipoDoc, string codValidacaoSerie, System.DateTime dataRegistoDe, bool dataRegistoDeSpecified, System.DateTime dataRegistoAte, bool dataRegistoAteSpecified, string estado, string meioProcessamento, object userState) {
            if ((this.consultarSeriesOperationCompleted == null)) {
                this.consultarSeriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarSeriesOperationCompleted);
            }
            this.InvokeAsync("consultarSeries", new object[] {
                        serie,
                        tipoSerie,
                        classeDoc,
                        tipoDoc,
                        codValidacaoSerie,
                        dataRegistoDe,
                        dataRegistoDeSpecified,
                        dataRegistoAte,
                        dataRegistoAteSpecified,
                        estado,
                        meioProcessamento}, this.consultarSeriesOperationCompleted, userState);
        }
        
        private void OnconsultarSeriesOperationCompleted(object arg) {
            if ((this.consultarSeriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarSeriesCompleted(this, new consultarSeriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://at.gov.pt/", ResponseNamespace="http://at.gov.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("anularSerieResp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesResp anularSerie([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string serie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string classeDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoDoc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string codValidacaoSerie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string motivo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool declaracaoNaoEmissao) {
            object[] results = this.Invoke("anularSerie", new object[] {
                        serie,
                        classeDoc,
                        tipoDoc,
                        codValidacaoSerie,
                        motivo,
                        declaracaoNaoEmissao});
            return ((seriesResp)(results[0]));
        }
        
        /// <remarks/>
        public void anularSerieAsync(string serie, string classeDoc, string tipoDoc, string codValidacaoSerie, string motivo, bool declaracaoNaoEmissao) {
            this.anularSerieAsync(serie, classeDoc, tipoDoc, codValidacaoSerie, motivo, declaracaoNaoEmissao, null);
        }
        
        /// <remarks/>
        public void anularSerieAsync(string serie, string classeDoc, string tipoDoc, string codValidacaoSerie, string motivo, bool declaracaoNaoEmissao, object userState) {
            if ((this.anularSerieOperationCompleted == null)) {
                this.anularSerieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnanularSerieOperationCompleted);
            }
            this.InvokeAsync("anularSerie", new object[] {
                        serie,
                        classeDoc,
                        tipoDoc,
                        codValidacaoSerie,
                        motivo,
                        declaracaoNaoEmissao}, this.anularSerieOperationCompleted, userState);
        }
        
        private void OnanularSerieOperationCompleted(object arg) {
            if ((this.anularSerieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.anularSerieCompleted(this, new anularSerieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class seriesResp {
        
        private seriesInfo infoSerieField;
        
        private operationResultInfo infoResultOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesInfo infoSerie {
            get {
                return this.infoSerieField;
            }
            set {
                this.infoSerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public operationResultInfo infoResultOper {
            get {
                return this.infoResultOperField;
            }
            set {
                this.infoResultOperField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class seriesInfo {
        
        private string serieField;
        
        private string tipoSerieField;
        
        private string classeDocField;
        
        private string tipoDocField;
        
        private string numInicialSeqField;
        
        private string numFinalSeqField;
        
        private System.DateTime dataInicioPrevUtilizField;
        
        private string seqUltimoDocEmitidoField;
        
        private string meioProcessamentoField;
        
        private string numCertSWFaturField;
        
        private string codValidacaoSerieField;
        
        private System.DateTime dataRegistoField;
        
        private string estadoField;
        
        private string motivoEstadoField;
        
        private string justificacaoField;
        
        private System.DateTime dataEstadoField;
        
        private string nifComunicouField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoSerie {
            get {
                return this.tipoSerieField;
            }
            set {
                this.tipoSerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classeDoc {
            get {
                return this.classeDocField;
            }
            set {
                this.classeDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDoc {
            get {
                return this.tipoDocField;
            }
            set {
                this.tipoDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numInicialSeq {
            get {
                return this.numInicialSeqField;
            }
            set {
                this.numInicialSeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numFinalSeq {
            get {
                return this.numFinalSeqField;
            }
            set {
                this.numFinalSeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime dataInicioPrevUtiliz {
            get {
                return this.dataInicioPrevUtilizField;
            }
            set {
                this.dataInicioPrevUtilizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string seqUltimoDocEmitido {
            get {
                return this.seqUltimoDocEmitidoField;
            }
            set {
                this.seqUltimoDocEmitidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string meioProcessamento {
            get {
                return this.meioProcessamentoField;
            }
            set {
                this.meioProcessamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numCertSWFatur {
            get {
                return this.numCertSWFaturField;
            }
            set {
                this.numCertSWFaturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codValidacaoSerie {
            get {
                return this.codValidacaoSerieField;
            }
            set {
                this.codValidacaoSerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime dataRegisto {
            get {
                return this.dataRegistoField;
            }
            set {
                this.dataRegistoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivoEstado {
            get {
                return this.motivoEstadoField;
            }
            set {
                this.motivoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string justificacao {
            get {
                return this.justificacaoField;
            }
            set {
                this.justificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dataEstado {
            get {
                return this.dataEstadoField;
            }
            set {
                this.dataEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nifComunicou {
            get {
                return this.nifComunicouField;
            }
            set {
                this.nifComunicouField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class consultSeriesResp {
        
        private seriesInfo[] infoSerieField;
        
        private operationResultInfo infoResultOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoSerie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesInfo[] infoSerie {
            get {
                return this.infoSerieField;
            }
            set {
                this.infoSerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public operationResultInfo infoResultOper {
            get {
                return this.infoResultOperField;
            }
            set {
                this.infoResultOperField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class operationResultInfo {
        
        private string codResultOperField;
        
        private string msgResultOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string codResultOper {
            get {
                return this.codResultOperField;
            }
            set {
                this.codResultOperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgResultOper {
            get {
                return this.msgResultOperField;
            }
            set {
                this.msgResultOperField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void registarSerieCompletedEventHandler(object sender, registarSerieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registarSerieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registarSerieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public seriesResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((seriesResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void finalizarSerieCompletedEventHandler(object sender, finalizarSerieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class finalizarSerieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal finalizarSerieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public seriesResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((seriesResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void consultarSeriesCompletedEventHandler(object sender, consultarSeriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarSeriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarSeriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultSeriesResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultSeriesResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void anularSerieCompletedEventHandler(object sender, anularSerieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class anularSerieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal anularSerieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public seriesResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((seriesResp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591